"""Single-transverse-phase forward test for the q=20 Bessel retrieval.

This is the authoritative forward-model closure test for the presentation path.
It deliberately does not consume the legacy normalized z-order-to-radius map.

The measured z-stack is first used to retrieve one residual angular phase per
sampled input annulus.  Those rows are mapped to a *single transverse input-plane
phase* via rho_z = z tan(alpha).  That phase is then used in one common
band-limited angular-spectrum propagation model:

    ideal input
    ideal input * exp(+i psi_residual)       -> predicted measured distortion
    ideal input * exp(+i psi_residual) * exp(-i psi_residual)
                                             -> model correction closure

There is no independent longitudinal correction phase.  All z-dependence in the
predicted fields is generated by propagation.
"""
from __future__ import annotations

from pathlib import Path
import json
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import ndimage

from modal_vortex_bessel import load_first_scan, estimate_global_kr, find_dark_core_center
from q20_phase_physics import gauge_annular_phase_rows, cone_geometry, central_band_sections

for CODE_ROOT in Path(__file__).resolve().parents:
    if ((CODE_ROOT / "vbb_study").is_dir() or
            (CODE_ROOT / "Publication_Study" / "vbb_study").is_dir()):
        if str(CODE_ROOT) not in sys.path:
            sys.path.insert(0, str(CODE_ROOT))
        break
try:
    from vbb_study.equations.fields import make_xy_grid
    from vbb_study.equations.propagation import make_bl_asm_propagator
except ModuleNotFoundError:
    from Publication_Study.vbb_study.equations.fields import make_xy_grid
    from Publication_Study.vbb_study.equations.propagation import make_bl_asm_propagator

EPS = 1.0e-12


def _normalise(a: np.ndarray) -> np.ndarray:
    a = np.asarray(a, float)
    return a / max(float(np.max(a)), EPS)


def _corr_rmse(a: np.ndarray, b: np.ndarray, mask: np.ndarray) -> tuple[float, float]:
    av, bv = np.asarray(a)[mask], np.asarray(b)[mask]
    return (float(np.corrcoef(av, bv)[0, 1]),
            float(np.sqrt(np.mean((av - bv) ** 2))))


def _sample_measured(images, axis_um, pixel_pitch_m):
    X_um, Y_um = np.meshgrid(axis_um, axis_um, indexing="xy")
    out = []
    for image in images:
        cy, cx, _ = find_dark_core_center(image)
        yy = cy + Y_um * 1e-6 / pixel_pitch_m
        xx = cx + X_um * 1e-6 / pixel_pitch_m
        out.append(_normalise(ndimage.map_coordinates(
            image, [yy, xx], order=1, mode="constant", cval=0.0)))
    return np.stack(out)


def _sample_model_intensity(field, grid, axis_um):
    coord_px = axis_um * 1e-6 / float(grid["dx"]) + (int(grid["N"]) - 1) / 2
    xx, yy = np.meshgrid(coord_px, coord_px, indexing="xy")
    return _normalise(ndimage.map_coordinates(
        np.abs(field) ** 2, [yy, xx], order=1, mode="constant", cval=0.0))


def _map_residual_rows_to_grid(
    phase_rows_rad: np.ndarray,
    z_absolute_mm: np.ndarray,
    grid,
    *,
    wavelength_m: float,
    kr_m_inv: float,
) -> tuple[np.ndarray, tuple[float, float]]:
    """Map gauge-fixed annular residuals onto one physical transverse grid."""
    phase_rows = gauge_annular_phase_rows(np.asarray(phase_rows_rad, float))
    z_abs = np.asarray(z_absolute_mm, float)
    if phase_rows.shape[0] != len(z_abs):
        raise ValueError("one annular phase row is required for every z plane")
    order = np.argsort(z_abs)
    z_abs = z_abs[order]
    phase_rows = phase_rows[order]
    if np.any(z_abs <= 0) or np.any(np.diff(z_abs) <= 0):
        raise ValueError("absolute z positions must be positive and unique")

    geom = cone_geometry(wavelength_m, kr_m_inv)
    z_for_radius_mm = grid["R"] / geom.tan_alpha * 1e3
    row_coord = np.interp(
        z_for_radius_mm, z_abs, np.arange(len(z_abs), dtype=float))
    valid = ((z_for_radius_mm >= z_abs[0]) & (z_for_radius_mm <= z_abs[-1]))

    phasor = np.exp(1j * phase_rows)
    phasor = np.concatenate([phasor, phasor[:, :1]], axis=1)
    theta_coord = np.mod(grid["PHI"], 2 * np.pi) / (2 * np.pi) * phase_rows.shape[1]
    real = ndimage.map_coordinates(
        phasor.real, [row_coord, theta_coord], order=1, mode="nearest")
    imag = ndimage.map_coordinates(
        phasor.imag, [row_coord, theta_coord], order=1, mode="nearest")
    residual = np.angle(real + 1j * imag)
    residual[~valid] = 0.0
    annulus = (float(z_abs[0] * 1e-3 * geom.tan_alpha),
               float(z_abs[-1] * 1e-3 * geom.tan_alpha))
    return residual, annulus


def _fit_absolute_z_end_from_ideal(
    measured: np.ndarray,
    z_relative_mm: np.ndarray,
    prop_ideal,
    grid,
    axis_um: np.ndarray,
    roi: np.ndarray,
    *,
    search_min_mm: float = 18.0,
    search_max_mm: float = 30.0,
) -> tuple[float, pd.DataFrame]:
    """Fit only the unknown camera/input axial offset using the ideal field.

    The retrieved aberration is not used in this nuisance-parameter fit, so the
    phase-error model cannot tune its own z registration to the measured error.
    """
    anchors = np.unique(np.array([0, len(measured)//2, len(measured)-1], dtype=int))
    rows = []

    def evaluate(end_mm: float):
        corr = []
        for iz in anchors:
            z_abs = end_mm + z_relative_mm[iz]
            if z_abs <= 0:
                return
            model = _sample_model_intensity(prop_ideal(z_abs * 1e-3), grid, axis_um)
            corr.append(_corr_rmse(measured[iz], model, roi)[0])
        rows.append({
            "absolute_z_at_relative_zero_mm": float(end_mm),
            "mean_anchor_ideal_correlation": float(np.mean(corr)),
        })

    for end in np.arange(search_min_mm, search_max_mm + 1e-9, 2.0):
        evaluate(float(end))
    coarse = pd.DataFrame(rows)
    best = float(coarse.loc[coarse.mean_anchor_ideal_correlation.idxmax(),
                            "absolute_z_at_relative_zero_mm"])
    for end in np.arange(max(search_min_mm, best - 1.5),
                         min(search_max_mm, best + 1.5) + 1e-9, 0.25):
        if not np.any(np.isclose(coarse.absolute_z_at_relative_zero_mm, end)):
            evaluate(float(end))
    table = pd.DataFrame(rows).sort_values("absolute_z_at_relative_zero_mm")
    best = float(table.loc[table.mean_anchor_ideal_correlation.idxmax(),
                           "absolute_z_at_relative_zero_mm"])
    return best, table


def run_single_transverse_phase_test(
    data_dir,
    phase_rows_path,
    output_dir,
    *,
    z_relative_mm=np.arange(-17, 1),
    wavelength_m=1030e-9,
    pixel_pitch_m=5.5e-6,
    q=20,
    beam_radius_m=2.0e-3,
    grid_n=1024,
    grid_dx_m=5.5e-6,
    view_limit_um=180.0,
    view_size=181,
    absolute_z_at_relative_zero_mm: float | None = None,
):
    data_dir = Path(data_dir)
    phase_rows_path = Path(phase_rows_path)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    images = load_first_scan(data_dir)
    z_relative_mm = np.asarray(z_relative_mm, float)
    if len(images) != len(z_relative_mm):
        raise ValueError("z_relative_mm must contain one position per measured plane")
    phase_rows = np.load(phase_rows_path)
    if phase_rows.shape[0] != len(images):
        raise ValueError("annular phase rows do not match the measured z stack")

    kr_m_inv, _ = estimate_global_kr(images, pixel_pitch_m, q, .55)
    axis_um = np.linspace(-view_limit_um, view_limit_um, view_size)
    measured = _sample_measured(images, axis_um, pixel_pitch_m)
    Xv, Yv = np.meshgrid(axis_um, axis_um, indexing="xy")
    roi = np.hypot(Xv, Yv) <= 160.0

    grid = make_xy_grid(grid_n, grid_dx_m)
    aperture = np.exp(-(grid["R"] / beam_radius_m) ** 2)
    ideal_input = aperture * np.exp(1j * (q * grid["PHI"] - kr_m_inv * grid["R"]))
    prop_ideal = make_bl_asm_propagator(ideal_input, grid, wavelength_m)

    if absolute_z_at_relative_zero_mm is None:
        absolute_end_mm, z_search = _fit_absolute_z_end_from_ideal(
            measured, z_relative_mm, prop_ideal, grid, axis_um, roi)
    else:
        absolute_end_mm = float(absolute_z_at_relative_zero_mm)
        z_search = pd.DataFrame([{
            "absolute_z_at_relative_zero_mm": absolute_end_mm,
            "mean_anchor_ideal_correlation": np.nan,
        }])
    z_absolute_mm = absolute_end_mm + z_relative_mm
    if np.any(z_absolute_mm <= 0):
        raise ValueError("fitted/provided absolute z offset places a measured plane at z<=0")

    residual_phase, annulus_m = _map_residual_rows_to_grid(
        phase_rows, z_absolute_mm, grid,
        wavelength_m=wavelength_m, kr_m_inv=kr_m_inv)
    error_input = ideal_input * np.exp(1j * residual_phase)
    corrected_input = error_input * np.exp(-1j * residual_phase)
    prop_error = make_bl_asm_propagator(error_input, grid, wavelength_m)
    prop_corrected = make_bl_asm_propagator(corrected_input, grid, wavelength_m)

    ideal_stack, error_stack, corrected_stack = [], [], []
    for z_abs_mm in z_absolute_mm:
        z_m = z_abs_mm * 1e-3
        ideal_stack.append(_sample_model_intensity(prop_ideal(z_m), grid, axis_um))
        error_stack.append(_sample_model_intensity(prop_error(z_m), grid, axis_um))
        corrected_stack.append(_sample_model_intensity(prop_corrected(z_m), grid, axis_um))
    ideal_stack = np.stack(ideal_stack)
    error_stack = np.stack(error_stack)
    corrected_stack = np.stack(corrected_stack)

    rows = []
    for iz, z_rel in enumerate(z_relative_mm):
        ci, ei = _corr_rmse(measured[iz], ideal_stack[iz], roi)
        ce, ee = _corr_rmse(measured[iz], error_stack[iz], roi)
        rows.append({
            "z_relative_mm": float(z_rel),
            "z_absolute_model_mm": float(z_absolute_mm[iz]),
            "measured_vs_ideal_corr": ci,
            "measured_vs_error_model_corr": ce,
            "measured_vs_ideal_rmse": ei,
            "measured_vs_error_model_rmse": ee,
        })
    metrics = pd.DataFrame(rows)
    metrics.to_csv(output_dir / "single_transverse_phase_metrics.csv", index=False)
    z_search.to_csv(output_dir / "ideal_only_absolute_z_registration.csv", index=False)

    np.savez_compressed(
        output_dir / "single_transverse_phase_stacks.npz",
        x_um=axis_um,
        z_relative_mm=z_relative_mm,
        z_absolute_model_mm=z_absolute_mm,
        measured=measured,
        ideal=ideal_stack,
        error_model=error_stack,
        corrected_model=corrected_stack,
        residual_input_phase_rad=residual_phase.astype(np.float32),
    )

    corr_gain = float(metrics.measured_vs_error_model_corr.median()
                      - metrics.measured_vs_ideal_corr.median())
    rmse_gain = float(metrics.measured_vs_ideal_rmse.median()
                      - metrics.measured_vs_error_model_rmse.median())
    supports = bool(corr_gain >= 0.03 and rmse_gain > 0)
    summary = {
        "test": "one transverse residual phase, one common propagation model",
        "planes": int(len(images)),
        "q_target_retained_in_ideal_field": int(q),
        "target_qtheta_in_residual": False,
        "independent_longitudinal_correction_phase": False,
        "kr_rad_per_um": float(kr_m_inv * 1e-6),
        "absolute_z_at_relative_zero_mm_fitted_from_ideal_only": absolute_end_mm,
        "sampled_input_annulus_radius_mm": [annulus_m[0] * 1e3, annulus_m[1] * 1e3],
        "median_measured_vs_ideal_corr": float(metrics.measured_vs_ideal_corr.median()),
        "median_measured_vs_error_model_corr": float(metrics.measured_vs_error_model_corr.median()),
        "error_model_correlation_gain_over_ideal": corr_gain,
        "median_measured_vs_ideal_rmse": float(metrics.measured_vs_ideal_rmse.median()),
        "median_measured_vs_error_model_rmse": float(metrics.measured_vs_error_model_rmse.median()),
        "error_model_rmse_reduction_from_ideal": rmse_gain,
        "supports_retrieved_phase_as_cause_of_measured_distortion": supports,
        "corrected_model_interpretation": (
            "model closure only: the same retrieved residual is exactly conjugated at the input plane"
        ),
        "hardware_ready": False,
        "remaining_calibration": (
            "absolute input/SLM annulus radius, relay magnification, rotation, parity, beam footprint and phase LUT; "
            "then low-gain application plus a new measured z-stack"
        ),
    }
    (output_dir / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")

    stacks = (measured, error_stack, corrected_stack)
    titles = ("LAB MEASURED", "MODEL + RETRIEVED RESIDUAL",
              "MODEL AFTER CONJUGATE CORRECTION")
    fig, axes = plt.subplots(2, 3, figsize=(17.5, 9), constrained_layout=True,
                             sharex=True, sharey=True)
    for col, (stack, title) in enumerate(zip(stacks, titles)):
        xz, yz = central_band_sections(stack, half_width_px=2)
        for row, (arr, label) in enumerate(((xz, "x-z"), (yz, "y-z"))):
            shown = axes[row, col].imshow(
                arr, origin="lower", aspect="auto", cmap="inferno", vmin=0, vmax=1,
                extent=[axis_um[0], axis_um[-1], z_relative_mm[0], z_relative_mm[-1]],
                interpolation="nearest")
            axes[row, col].axvline(0, color="cyan", lw=.55, alpha=.6)
            axes[row, col].set(title=f"{label} | {title}",
                               xlabel="signed transverse coordinate (um)",
                               ylabel="relative z (mm)")
    fig.colorbar(shown, ax=axes, label="plane-normalized intensity", shrink=.82)
    fig.suptitle(
        "q=20 single-transverse-phase forward test\n"
        "z-dependence is generated by propagation; no longitudinal correction map is fitted",
        fontsize=14)
    fig.savefig(output_dir / "single_transverse_phase_forward_model.png",
                dpi=420, bbox_inches="tight")
    plt.close(fig)

    return metrics, summary


if __name__ == "__main__":
    here = Path(__file__).resolve().parent
    modal = here / "outputs" / "slm_closed_loop_alignment" / "modal_q20"
    _, report = run_single_transverse_phase_test(
        here / "z-scan 2 1010",
        modal / "annular_aberration_phase.npy",
        modal / "single_transverse_phase_forward_test",
        z_relative_mm=np.arange(-17, 1))
    print(json.dumps(report, indent=2))
