"""Experiment-to-simulation matching for the vortex/Bessel digital twin.

This package deliberately compares measured intensity stacks against fields
regenerated by the canonical physical route.  Rendered atlas images are never
used as inference inputs.
"""

from .experimental_stack import IntensityStack, load_experimental_stack, preprocess_stack
from .candidate_models import FAMILY_REGISTRY, DEFAULT_MATCH_FAMILIES, CandidateFamily
from .matcher import CandidateScore, MatchResult, match_error_candidates, simulate_candidate_stack
from .miao_handoff import MiaoHandoff, build_miao_handoff

__all__ = [
    "IntensityStack",
    "load_experimental_stack",
    "preprocess_stack",
    "CandidateFamily",
    "FAMILY_REGISTRY",
    "DEFAULT_MATCH_FAMILIES",
    "CandidateScore",
    "MatchResult",
    "match_error_candidates",
    "simulate_candidate_stack",
    "MiaoHandoff",
    "build_miao_handoff",
]
