"""Figure/output governance registry for Stage 8.6.

The registry is intentionally conservative: final export code must ask this
module before using an output. Unknown, legacy, or rejected paths are blocked by
default.
"""

from __future__ import annotations

import fnmatch
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable

import pandas as pd

from . import advanced, capsule, lab_realism, materials, tables, vector
from .captions import caption_gate

FIGURE_REGISTRY_SCHEMA_VERSION = "1.0.0"

STATUS_VALUES = {
    "final_export_allowed",
    "diagnostic_allowed",
    "exploratory_only",
    "legacy_quarantined",
    "rejected",
}

VISUAL_QUALITY_STATUS = {
    "table_or_metadata",
    "caption_gated",
    "diagnostic_only",
    "needs_regeneration",
    "legacy_not_reviewed",
    "rejected",
}

PIXELATION_STATUS = {
    "not_applicable",
    "acceptable",
    "review_at_manuscript_size",
    "dense_or_compressed",
    "unknown",
}


class PublicationExportGateError(ValueError):
    """Raised when export code attempts to use a blocked output."""


@dataclass(frozen=True)
class FigureRegistryItem:
    """One governed output family.

    ``output_path`` may be a concrete path or a fnmatch-style path pattern.
    """

    output_path: str
    stage: str
    notebook_source: str
    source_csv: str
    source_run_id: str
    source_schema_version: str
    status: str
    reason: str
    caveat_required: bool
    model_level: str
    hardware_status: str
    material_model_status: str
    propagation_power_label: str
    visual_quality_status: str
    pixelation_status: str
    final_export_allowed: bool
    visualisation_type: str
    caption_gate_key: str
    recommended_action: str
    interpolation_used: str = "unknown"
    interpolation_label_present: str = "unknown"
    units_present: str = "unknown"
    colourbar_label_present: str = "unknown"
    qa_label_visible: str = "unknown"

    def __post_init__(self) -> None:
        if self.status not in STATUS_VALUES:
            raise ValueError(f"Invalid registry status: {self.status!r}")
        if self.visual_quality_status not in VISUAL_QUALITY_STATUS:
            raise ValueError(f"Invalid visual_quality_status: {self.visual_quality_status!r}")
        if self.pixelation_status not in PIXELATION_STATUS:
            raise ValueError(f"Invalid pixelation_status: {self.pixelation_status!r}")
        if bool(self.final_export_allowed) != (self.status == "final_export_allowed"):
            raise ValueError("final_export_allowed must match status == 'final_export_allowed'.")


def _item(
    output_path: str,
    stage: str,
    notebook_source: str,
    source_csv: str,
    status: str,
    reason: str,
    caption_gate_key: str,
    *,
    source_schema_version: str = "unknown",
    source_run_id: str = "unknown",
    caveat_required: bool = True,
    model_level: str = "not_applicable",
    hardware_status: str = "not_applicable",
    material_model_status: str = "not_applicable",
    propagation_power_label: str = "not_applicable",
    visual_quality_status: str = "caption_gated",
    pixelation_status: str = "review_at_manuscript_size",
    visualisation_type: str = "output_family",
    recommended_action: str = "Use registry gate before export.",
    interpolation_used: str = "unknown",
    interpolation_label_present: str = "unknown",
    units_present: str = "unknown",
    colourbar_label_present: str = "unknown",
    qa_label_visible: str = "unknown",
) -> FigureRegistryItem:
    return FigureRegistryItem(
        output_path=output_path,
        stage=stage,
        notebook_source=notebook_source,
        source_csv=source_csv,
        source_run_id=source_run_id,
        source_schema_version=source_schema_version,
        status=status,
        reason=reason,
        caveat_required=bool(caveat_required),
        model_level=model_level,
        hardware_status=hardware_status,
        material_model_status=material_model_status,
        propagation_power_label=propagation_power_label,
        visual_quality_status=visual_quality_status,
        pixelation_status=pixelation_status,
        final_export_allowed=status == "final_export_allowed",
        visualisation_type=visualisation_type,
        caption_gate_key=caption_gate_key,
        recommended_action=recommended_action,
        interpolation_used=interpolation_used,
        interpolation_label_present=interpolation_label_present,
        units_present=units_present,
        colourbar_label_present=colourbar_label_present,
        qa_label_visible=qa_label_visible,
    )


_REGISTRY_ITEMS: tuple[FigureRegistryItem, ...] = (
    _item(
        "Publication_Study/outputs/csv/README.md",
        "output_documentation",
        "manual documentation",
        "",
        "diagnostic_allowed",
        "Output naming documentation; not a figure/table for paper export.",
        "governance_registry",
        source_schema_version=FIGURE_REGISTRY_SCHEMA_VERSION,
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="documentation",
        recommended_action="Use for traceability and route selection.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="not_applicable",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/csv/sas_self_checks.csv",
        "validation",
        "notebooks/scalar/05_scalar_validation_suite.ipynb",
        "Publication_Study/outputs/csv/sas_self_checks.csv",
        "final_export_allowed",
        "SAS self-check table used for numerical QA traceability.",
        "validation",
        source_schema_version=tables.SCALAR_OUTPUT_SCHEMA_VERSION,
        model_level="validation",
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="validation_csv",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/csv/publication_exports/figure_output_registry.csv",
        "stage8_6_governance",
        "docs/16_figure_output_governance.md",
        "Publication_Study/outputs/csv/publication_exports/figure_output_registry.csv",
        "final_export_allowed",
        "Machine-readable final-export allow/quarantine registry.",
        "governance_registry",
        source_schema_version=FIGURE_REGISTRY_SCHEMA_VERSION,
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="registry_csv",
        recommended_action="Use as the authoritative export gate.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="not_applicable",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/csv/publication_exports/figure_visual_quality_audit.csv",
        "stage8_6_governance",
        "docs/16_figure_output_governance.md",
        "Publication_Study/outputs/csv/publication_exports/figure_visual_quality_audit.csv",
        "final_export_allowed",
        "Machine-readable visual QA table derived from Stage 8.5 and Stage 8.6.",
        "governance_registry",
        source_schema_version=FIGURE_REGISTRY_SCHEMA_VERSION,
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="visual_qa_csv",
        recommended_action="Review before final report assembly.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="not_applicable",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/csv/publication_study/scalar_shortlist_realistic_summary_publication.csv",
        "scalar",
        "notebooks/scalar/02_scalar_ideal_vs_lab_diagnostics.ipynb",
        "Publication_Study/outputs/csv/publication_study/scalar_shortlist_realistic_summary_publication.csv",
        "final_export_allowed",
        "Canonical scalar publication-preset summary table.",
        "scalar_publication_preset",
        source_schema_version=tables.SCALAR_OUTPUT_SCHEMA_VERSION,
        model_level="scalar_paraxial",
        propagation_power_label="row_level",
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="canonical_csv",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/csv/publication_study/scalar_preset_comparison_fast_vs_publication.csv",
        "scalar",
        "notebooks/scalar/02_scalar_ideal_vs_lab_diagnostics.ipynb",
        "Publication_Study/outputs/csv/publication_study/scalar_preset_comparison_fast_vs_publication.csv",
        "final_export_allowed",
        "Preset-comparison table keeps fast versus publication QA differences visible.",
        "scalar_publication_preset",
        source_schema_version=tables.SCALAR_OUTPUT_SCHEMA_VERSION,
        model_level="scalar_paraxial",
        propagation_power_label="row_level",
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="comparison_csv",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/csv/publication_study/*validation*.csv",
        "validation",
        "notebooks/scalar/05_scalar_validation_suite.ipynb",
        "Publication_Study/outputs/csv/publication_study/validation_suite.csv",
        "final_export_allowed",
        "Canonical numerical validation CSV family.",
        "validation",
        source_schema_version=tables.SCALAR_OUTPUT_SCHEMA_VERSION,
        model_level="validation",
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="validation_csv",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/csv/stage_c/NB_*",
        "lab_realism",
        "notebooks/lab_realism/*",
        "Publication_Study/outputs/csv/stage_c/*.csv",
        "legacy_quarantined",
        "NB compatibility output retained for old notebooks; not final-export safe.",
        "diagnostic_legacy",
        source_schema_version=lab_realism.LAB_REALISM_SCHEMA_VERSION,
        model_level="lab_realistic",
        hardware_status="row_level",
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="not_applicable",
        visualisation_type="legacy_csv",
        recommended_action="Use non-NB stage_c canonical rows instead.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="unknown",
        colourbar_label_present="not_applicable",
        qa_label_visible="unknown",
    ),
    _item(
        "Publication_Study/outputs/csv/stage_c/*.csv",
        "lab_realism",
        "notebooks/lab_realism/01-04",
        "Publication_Study/outputs/csv/stage_c/*.csv",
        "final_export_allowed",
        "Current lab-realism route, objective/pupil, and first-order-filter CSV family.",
        "lab_realism",
        source_schema_version=lab_realism.LAB_REALISM_SCHEMA_VERSION,
        model_level="lab_realistic",
        hardware_status="row_level",
        propagation_power_label="row_level",
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="canonical_csv",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/csv/stage_d/NB_*",
        "through_sample",
        "notebooks/lab_realism/05_through_sample_interface.ipynb",
        "Publication_Study/outputs/csv/stage_d/through_sample_summary.csv",
        "legacy_quarantined",
        "NB through-sample compatibility output; canonical non-NB rows supersede it.",
        "diagnostic_legacy",
        source_schema_version=lab_realism.LAB_REALISM_SCHEMA_VERSION,
        model_level="interface_model",
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="not_applicable",
        visualisation_type="legacy_csv",
        recommended_action="Use through_sample_summary.csv for governed exports.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="unknown",
        colourbar_label_present="not_applicable",
        qa_label_visible="unknown",
    ),
    _item(
        "Publication_Study/outputs/csv/stage_d/through_sample_summary.csv",
        "through_sample",
        "notebooks/lab_realism/05_through_sample_interface.ipynb",
        "Publication_Study/outputs/csv/stage_d/through_sample_summary.csv",
        "final_export_allowed",
        "Canonical through-sample scalar interface summary table.",
        "lab_realism",
        source_schema_version=lab_realism.LAB_REALISM_SCHEMA_VERSION,
        model_level="interface_model",
        hardware_status="row_level",
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="canonical_csv",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/csv/stage_d/corrected_vs_uncorrected_metrics.csv",
        "through_sample",
        "notebooks/lab_realism/05_through_sample_interface.ipynb",
        "Publication_Study/outputs/csv/stage_d/corrected_vs_uncorrected_metrics.csv",
        "diagnostic_allowed",
        "Corrected-vs-uncorrected interface table is an ideal numerical diagnostic.",
        "interface_correction",
        source_schema_version=lab_realism.LAB_REALISM_SCHEMA_VERSION,
        model_level="interface_model",
        hardware_status="diagnostic_only",
        visual_quality_status="diagnostic_only",
        pixelation_status="not_applicable",
        visualisation_type="diagnostic_csv",
        recommended_action="Use only with ideal_numerical_correction caveat.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/csv/stage_d/*correction*.csv",
        "through_sample",
        "notebooks/lab_realism/05_through_sample_interface.ipynb",
        "Publication_Study/outputs/csv/stage_d/corrected_vs_uncorrected_metrics.csv",
        "diagnostic_allowed",
        "Interface correction is an ideal numerical diagnostic unless physically implemented.",
        "interface_correction",
        source_schema_version=lab_realism.LAB_REALISM_SCHEMA_VERSION,
        model_level="interface_model",
        hardware_status="diagnostic_only",
        visual_quality_status="diagnostic_only",
        pixelation_status="not_applicable",
        visualisation_type="diagnostic_csv",
        recommended_action="Use only with ideal_numerical_correction caveat.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/csv/stage_e/NB_*",
        "full_journey",
        "notebooks/lab_realism/06_full_source_to_sample_journey.ipynb",
        "Publication_Study/outputs/csv/stage_e/full_source_to_sample_journey_summary.csv",
        "legacy_quarantined",
        "NB full-journey compatibility output; canonical non-NB rows supersede it.",
        "diagnostic_legacy",
        source_schema_version=lab_realism.LAB_REALISM_SCHEMA_VERSION,
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="not_applicable",
        visualisation_type="legacy_csv",
        recommended_action="Use full_source_to_sample_journey_summary.csv.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="unknown",
        colourbar_label_present="not_applicable",
        qa_label_visible="unknown",
    ),
    _item(
        "Publication_Study/outputs/csv/stage_e/full_source_to_sample_journey_summary.csv",
        "full_journey",
        "notebooks/lab_realism/06_full_source_to_sample_journey.ipynb",
        "Publication_Study/outputs/csv/stage_e/full_source_to_sample_journey_summary.csv",
        "final_export_allowed",
        "Canonical full source-to-sample journey summary table.",
        "lab_realism",
        source_schema_version=lab_realism.LAB_REALISM_SCHEMA_VERSION,
        model_level="lab_realistic",
        hardware_status="row_level",
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="canonical_csv",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/csv/vector/vector_*.csv",
        "vector",
        "notebooks/vector/*.ipynb",
        "Publication_Study/outputs/csv/vector/vector_*.csv",
        "final_export_allowed",
        "Canonical vector/Jones route CSV family with hardware-status columns.",
        "vector_current_lab",
        source_schema_version=vector.VECTOR_OUTPUT_SCHEMA_VERSION,
        model_level="vector_jones",
        hardware_status="row_level",
        propagation_power_label="row_level",
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="canonical_csv",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/csv/vector/stage6_*",
        "vector",
        "notebooks/vector/*.ipynb",
        "Publication_Study/outputs/csv/vector/vector_ideal_vs_lab_case1_summary.csv",
        "diagnostic_allowed",
        "Compatibility vector CSV family; canonical vector_* rows should drive final exports.",
        "vector_current_lab",
        source_schema_version=vector.VECTOR_OUTPUT_SCHEMA_VERSION,
        model_level="vector_jones",
        hardware_status="row_level",
        visual_quality_status="diagnostic_only",
        pixelation_status="not_applicable",
        visualisation_type="compatibility_csv",
        recommended_action="Use vector_* canonical rows for final export.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/csv/digital_twin/nathan_vector_hexagon_*.csv",
        "digital_twin",
        "notebooks/digital_twin/*nathan_vector_hexagon*.ipynb",
        "Publication_Study/outputs/csv/digital_twin/nathan_vector_hexagon_axicon_output_routes.csv",
        "exploratory_only",
        "Nathan vector-hexagon digital-twin route comparison; exploratory air-side optical prediction.",
        "digital_twin_vector_hexagon",
        source_schema_version=FIGURE_REGISTRY_SCHEMA_VERSION,
        model_level="vector_jones",
        hardware_status="row_level",
        propagation_power_label="row_level",
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="exploratory_csv",
        recommended_action="Use for route-selection discussion only; do not treat as final publication export.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/csv/materials/material_*.csv",
        "materials",
        "notebooks/materials/*.ipynb",
        "Publication_Study/outputs/csv/materials/material_proxy_fluence_threshold_summary.csv",
        "final_export_allowed",
        "Canonical materials-proxy CSV family with calibration-status columns.",
        "materials_proxy",
        source_schema_version=materials.MATERIAL_OUTPUT_SCHEMA_VERSION,
        model_level="material_proxy",
        material_model_status="row_level",
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="canonical_csv",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/csv/materials/07_materials_design_table.csv",
        "materials",
        "notebooks/materials/03_application_design_tables.ipynb",
        "Publication_Study/outputs/csv/materials/material_application_design_table.csv",
        "diagnostic_allowed",
        "Compatibility table retained for old path references.",
        "materials_proxy",
        source_schema_version=materials.MATERIAL_OUTPUT_SCHEMA_VERSION,
        model_level="material_proxy",
        material_model_status="planning_proxy",
        visual_quality_status="diagnostic_only",
        pixelation_status="not_applicable",
        visualisation_type="compatibility_csv",
        recommended_action="Use material_application_design_table.csv for governed exports.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/csv/capsule/*.csv",
        "capsule",
        "notebooks/advanced/01_capsule_weld_feature_design.ipynb",
        "Publication_Study/outputs/csv/capsule/capsule_weld_feature_design_summary.csv",
        "final_export_allowed",
        "Canonical capsule/weld-feature geometry-proxy CSV family.",
        "capsule_proxy",
        source_schema_version=capsule.CAPSULE_OUTPUT_SCHEMA_VERSION,
        model_level="geometry_proxy",
        material_model_status="planning_proxy",
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="canonical_csv",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/csv/advanced/*.csv",
        "advanced",
        "notebooks/advanced/02-03",
        "Publication_Study/outputs/csv/advanced/*.csv",
        "final_export_allowed",
        "Canonical Stage 8 advanced-beam CSV family with propagation/hardware-status columns.",
        "advanced_hex_polygonal_discrete",
        source_schema_version=advanced.ADVANCED_BEAM_OUTPUT_SCHEMA_VERSION,
        model_level="row_level",
        hardware_status="row_level",
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="canonical_csv",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/figures/publication_study/sas_validation_*.png*",
        "validation",
        "notebooks/scalar/05_scalar_validation_suite.ipynb",
        "Publication_Study/outputs/csv/publication_study/sas_validation_summary.csv",
        "final_export_allowed",
        "Canonical validation figures; resampling/retained-power caveat required.",
        "validation",
        source_schema_version=tables.SCALAR_OUTPUT_SCHEMA_VERSION,
        model_level="validation",
        visualisation_type="validation_figure",
        units_present="yes",
        colourbar_label_present="yes",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/figures/publication_study/03_sweep_*_heatmap.png*",
        "scalar",
        "notebooks/scalar/04_scalar_parameter_sweeps.ipynb",
        "Publication_Study/outputs/csv/publication_study/03_sweep_*_publication.csv",
        "final_export_allowed",
        "Scalar sweep heatmap family; failed/marginal cells must remain visible.",
        "scalar_publication_preset",
        source_schema_version=tables.SCALAR_OUTPUT_SCHEMA_VERSION,
        model_level="scalar_paraxial",
        propagation_power_label="row_level",
        visualisation_type="heatmap",
        interpolation_used="yes",
        interpolation_label_present="review_required",
        units_present="yes",
        colourbar_label_present="yes",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/figures/publication_study/radial_profile_overlay.png*",
        "scalar",
        "notebooks/publication_exports/03_report_export.ipynb",
        "Publication_Study/outputs/csv/publication_study/scalar_shortlist_realistic_summary_publication.csv",
        "final_export_allowed",
        "Lab-facing scalar radial-profile comparison with shared caveat requirement.",
        "scalar_publication_preset",
        source_schema_version=tables.SCALAR_OUTPUT_SCHEMA_VERSION,
        model_level="scalar_paraxial",
        visualisation_type="line_plot",
        interpolation_used="yes",
        interpolation_label_present="review_required",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/figures/publication_study/axial_xz_traces.png*",
        "scalar",
        "notebooks/publication_exports/03_report_export.ipynb",
        "Publication_Study/outputs/csv/publication_study/scalar_shortlist_realistic_summary_publication.csv",
        "final_export_allowed",
        "Scalar XZ/axial trace comparison; display normalization caveat required.",
        "scalar_publication_preset",
        source_schema_version=tables.SCALAR_OUTPUT_SCHEMA_VERSION,
        model_level="scalar_paraxial",
        visualisation_type="xz_trace_figure",
        interpolation_used="yes",
        interpolation_label_present="review_required",
        units_present="yes",
        colourbar_label_present="yes",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/figures/publication_study/shortlist_lab_comparison.png*",
        "scalar",
        "notebooks/publication_exports/03_report_export.ipynb",
        "Publication_Study/outputs/csv/publication_study/scalar_shortlist_realistic_summary_publication.csv",
        "final_export_allowed",
        "Scalar shortlist comparison; hardware/power QA labels must stay visible.",
        "scalar_publication_preset",
        source_schema_version=tables.SCALAR_OUTPUT_SCHEMA_VERSION,
        model_level="scalar_paraxial",
        propagation_power_label="row_level",
        visualisation_type="comparison_figure",
        interpolation_used="no",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/figures/publication_study/vortex_charge_*.png*",
        "scalar",
        "notebooks/publication_exports/03_report_export.ipynb",
        "Publication_Study/outputs/csv/publication_study/vortex_charge_sweep.csv",
        "final_export_allowed",
        "Vortex charge comparison figure family; charge/ring caveats required.",
        "scalar_publication_preset",
        source_schema_version=tables.SCALAR_OUTPUT_SCHEMA_VERSION,
        model_level="scalar_paraxial",
        visualisation_type="comparison_figure",
        units_present="yes",
        colourbar_label_present="yes",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/figures/publication_study/ell_family_scaling.png*",
        "scalar",
        "notebooks/scalar/04_scalar_parameter_sweeps.ipynb",
        "Publication_Study/outputs/csv/publication_study/ell_family_comparison.csv",
        "final_export_allowed",
        "Charge-family scaling plot with scalar/vortex metric labels.",
        "scalar_publication_preset",
        source_schema_version=tables.SCALAR_OUTPUT_SCHEMA_VERSION,
        model_level="scalar_paraxial",
        visualisation_type="line_plot",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/figures/publication_study/ell*_diagnostics.png*",
        "scalar",
        "notebooks/scalar/02_scalar_ideal_vs_lab_diagnostics.ipynb",
        "Publication_Study/outputs/csv/publication_study/ell*_summary.csv",
        "diagnostic_allowed",
        "Fast/detail diagnostic figure; not the final paper figure without review.",
        "scalar_fast_preset",
        source_schema_version=tables.SCALAR_OUTPUT_SCHEMA_VERSION,
        model_level="scalar_paraxial",
        propagation_power_label="row_level",
        visual_quality_status="diagnostic_only",
        pixelation_status="acceptable",
        visualisation_type="diagnostic_figure",
        recommended_action="Use only as diagnostic or regenerate under publication preset.",
        units_present="yes",
        colourbar_label_present="yes",
        qa_label_visible="review_required",
    ),
    _item(
        "Publication_Study/outputs/figures/publication_study/ell*_plane_montage.png*",
        "scalar",
        "notebooks/scalar/02_scalar_ideal_vs_lab_diagnostics.ipynb",
        "Publication_Study/outputs/csv/publication_study/ell*_summary.csv",
        "diagnostic_allowed",
        "Plane montage is useful for review but needs normalization/scale review before paper export.",
        "scalar_fast_preset",
        source_schema_version=tables.SCALAR_OUTPUT_SCHEMA_VERSION,
        model_level="scalar_paraxial",
        visual_quality_status="diagnostic_only",
        pixelation_status="acceptable",
        visualisation_type="plane_montage",
        recommended_action="Use only as diagnostic or regenerate with shared scale labels.",
        interpolation_used="yes",
        interpolation_label_present="review_required",
        units_present="yes",
        colourbar_label_present="review_required",
        qa_label_visible="review_required",
    ),
    _item(
        "Publication_Study/outputs/figures/publication_study/*.png*",
        "scalar_or_compatibility",
        "notebooks/scalar and publication_exports",
        "Publication_Study/outputs/csv/publication_study/*.csv",
        "diagnostic_allowed",
        "Publication-study figure not explicitly allow-listed; useful for review but blocked from final export.",
        "diagnostic_legacy",
        source_schema_version=tables.SCALAR_OUTPUT_SCHEMA_VERSION,
        model_level="mixed",
        visual_quality_status="diagnostic_only",
        pixelation_status="review_at_manuscript_size",
        visualisation_type="publication_study_diagnostic_figure",
        recommended_action="Add a specific registry allow-list entry before final export.",
        interpolation_used="unknown",
        interpolation_label_present="review_required",
        units_present="unknown",
        colourbar_label_present="unknown",
        qa_label_visible="review_required",
    ),
    _item(
        "Publication_Study/outputs/csv/publication_study/*.csv",
        "scalar_or_compatibility",
        "notebooks/scalar and publication_exports",
        "Publication_Study/outputs/csv/publication_study/*.csv",
        "diagnostic_allowed",
        "Publication-study CSV not explicitly allow-listed; may be compatibility, atlas, or diagnostic output.",
        "scalar_publication_preset",
        source_schema_version=tables.SCALAR_OUTPUT_SCHEMA_VERSION,
        model_level="mixed",
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="publication_study_diagnostic_csv",
        recommended_action="Use only if a final-export allow-list entry exists or is added.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="unknown",
        colourbar_label_present="not_applicable",
        qa_label_visible="review_required",
    ),
    _item(
        "Publication_Study/outputs/figures/stage_c/*.png*",
        "lab_realism",
        "notebooks/lab_realism/01-04",
        "Publication_Study/outputs/csv/stage_c/*.csv",
        "final_export_allowed",
        "Current lab-realism figure family; route and plane labels required.",
        "lab_realism",
        source_schema_version=lab_realism.LAB_REALISM_SCHEMA_VERSION,
        model_level="lab_realistic",
        hardware_status="row_level",
        visualisation_type="lab_realism_figure",
        units_present="yes",
        colourbar_label_present="yes",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/figures/stage_d/NB_*",
        "through_sample",
        "notebooks/lab_realism/05_through_sample_interface.ipynb",
        "Publication_Study/outputs/csv/stage_d/through_sample_summary.csv",
        "legacy_quarantined",
        "NB through-sample figures are compatibility copies.",
        "diagnostic_legacy",
        source_schema_version=lab_realism.LAB_REALISM_SCHEMA_VERSION,
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="unknown",
        visualisation_type="legacy_figure",
        recommended_action="Use non-NB through-sample figures.",
    ),
    _item(
        "Publication_Study/outputs/figures/stage_d/through_sample_*.png*",
        "through_sample",
        "notebooks/lab_realism/05_through_sample_interface.ipynb",
        "Publication_Study/outputs/csv/stage_d/through_sample_summary.csv",
        "final_export_allowed",
        "Through-sample figure family with planar scalar interface caveat.",
        "lab_realism",
        source_schema_version=lab_realism.LAB_REALISM_SCHEMA_VERSION,
        model_level="interface_model",
        visualisation_type="through_sample_figure",
        units_present="yes",
        colourbar_label_present="yes",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/figures/stage_e/NB_*",
        "full_journey",
        "notebooks/lab_realism/06_full_source_to_sample_journey.ipynb",
        "Publication_Study/outputs/csv/stage_e/full_source_to_sample_journey_summary.csv",
        "legacy_quarantined",
        "NB full-journey figures are compatibility copies.",
        "diagnostic_legacy",
        source_schema_version=lab_realism.LAB_REALISM_SCHEMA_VERSION,
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="unknown",
        visualisation_type="legacy_figure",
        recommended_action="Use non-NB full-source-to-sample figures.",
    ),
    _item(
        "Publication_Study/outputs/figures/stage_e/full_source_to_sample_journey_*.png*",
        "full_journey",
        "notebooks/lab_realism/06_full_source_to_sample_journey.ipynb",
        "Publication_Study/outputs/csv/stage_e/full_source_to_sample_journey_summary.csv",
        "final_export_allowed",
        "Full source-to-sample figure family with route and plane labels.",
        "lab_realism",
        source_schema_version=lab_realism.LAB_REALISM_SCHEMA_VERSION,
        model_level="lab_realistic",
        hardware_status="row_level",
        visualisation_type="full_journey_figure",
        units_present="yes",
        colourbar_label_present="yes",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/figures/vector/*.png*",
        "vector",
        "notebooks/vector/*.ipynb",
        "Publication_Study/outputs/csv/vector/vector_*.csv",
        "final_export_allowed",
        "Canonical vector figure family with Case-1 caveat requirement.",
        "vector_current_lab",
        source_schema_version=vector.VECTOR_OUTPUT_SCHEMA_VERSION,
        model_level="vector_jones",
        hardware_status="row_level",
        visualisation_type="vector_figure",
        units_present="yes",
        colourbar_label_present="yes",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/figures/capsule/*.png*",
        "capsule",
        "notebooks/advanced/01_capsule_weld_feature_design.ipynb",
        "Publication_Study/outputs/csv/capsule/*.csv",
        "final_export_allowed",
        "Future canonical capsule figure family; proxy caveat required.",
        "capsule_proxy",
        source_schema_version=capsule.CAPSULE_OUTPUT_SCHEMA_VERSION,
        model_level="geometry_proxy",
        material_model_status="planning_proxy",
        visualisation_type="capsule_proxy_figure",
        units_present="yes",
        colourbar_label_present="yes",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/figures/stage9_capsule/*.png*",
        "capsule",
        "notebooks/advanced/01_capsule_weld_feature_design.ipynb",
        "Publication_Study/outputs/csv/capsule/*.csv",
        "diagnostic_allowed",
        "Old Stage 9 path retained for review; canonical capsule figures should be regenerated under capsule/ before final export.",
        "capsule_proxy",
        source_schema_version=capsule.CAPSULE_OUTPUT_SCHEMA_VERSION,
        model_level="geometry_proxy",
        material_model_status="planning_proxy",
        visual_quality_status="diagnostic_only",
        pixelation_status="review_at_manuscript_size",
        visualisation_type="capsule_proxy_figure",
        recommended_action="Regenerate or copy through governed capsule figure path before final export.",
        units_present="yes",
        colourbar_label_present="yes",
        qa_label_visible="review_required",
    ),
    _item(
        "Publication_Study/outputs/figures/interface_correction/*.png*",
        "through_sample",
        "notebooks/lab_realism/05_through_sample_interface.ipynb",
        "Publication_Study/outputs/csv/stage_d/*correction*.csv",
        "diagnostic_allowed",
        "Interface-correction figures are diagnostic unless physically implemented.",
        "interface_correction",
        source_schema_version=lab_realism.LAB_REALISM_SCHEMA_VERSION,
        model_level="interface_model",
        hardware_status="diagnostic_only",
        visual_quality_status="diagnostic_only",
        pixelation_status="acceptable",
        visualisation_type="diagnostic_figure",
        recommended_action="Use only with ideal_numerical_correction caveat.",
        units_present="yes",
        colourbar_label_present="yes",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/figures/polarized_train/*.png*",
        "vector_advanced",
        "legacy polarized train notebooks",
        "Publication_Study/outputs/csv/polarized_train/*.csv",
        "diagnostic_allowed",
        "Polarized-train figures are route diagnostics and not current-lab radial/azimuthal proof.",
        "vector_current_lab",
        source_schema_version=vector.VECTOR_OUTPUT_SCHEMA_VERSION,
        model_level="vector_jones",
        hardware_status="diagnostic_only",
        visual_quality_status="diagnostic_only",
        pixelation_status="review_at_manuscript_size",
        visualisation_type="diagnostic_figure",
        recommended_action="Use only as diagnostic unless regenerated under canonical vector route.",
        units_present="yes",
        colourbar_label_present="yes",
        qa_label_visible="review_required",
    ),
    _item(
        "Publication_Study/outputs/figures/stage_f/*",
        "materials_legacy",
        "old Stage F compatibility notebooks",
        "Publication_Study/outputs/csv/materials/material_*.csv",
        "legacy_quarantined",
        "Old materials/capsule figures can imply calibrated material modification.",
        "diagnostic_legacy",
        source_schema_version=materials.MATERIAL_OUTPUT_SCHEMA_VERSION,
        model_level="material_proxy",
        material_model_status="planning_proxy",
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="unknown",
        visualisation_type="legacy_figure",
        recommended_action="Use canonical materials/capsule CSVs and regenerate figures with proxy caveats.",
    ),
    _item(
        "Publication_Study/outputs/figures/stage_h*/*",
        "advanced_legacy",
        "old advanced notebooks",
        "Publication_Study/outputs/csv/advanced/*.csv",
        "legacy_quarantined",
        "Old hex/sixfold figures predate the Stage 8 canonical schema.",
        "diagnostic_legacy",
        source_schema_version=advanced.ADVANCED_BEAM_OUTPUT_SCHEMA_VERSION,
        model_level="diagnostic_only",
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="unknown",
        visualisation_type="legacy_figure",
        recommended_action="Use canonical advanced CSVs and regenerate figures under Stage 8 labels.",
    ),
    _item(
        "Publication_Study/outputs/figures/stage10_discrete/*",
        "advanced_legacy",
        "old advanced discrete notebook",
        "Publication_Study/outputs/csv/advanced/discrete_nfold_beam_summary.csv",
        "legacy_quarantined",
        "Old discrete figures can overclaim nondiffracting or propagation-stable behavior.",
        "diagnostic_legacy",
        source_schema_version=advanced.ADVANCED_BEAM_OUTPUT_SCHEMA_VERSION,
        model_level="diagnostic_only",
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="dense_or_compressed",
        visualisation_type="legacy_figure",
        recommended_action="Regenerate from advanced/discrete_nfold_*.csv with propagation-status labels.",
    ),
    _item(
        "Publication_Study/outputs/figures/polygonal_hex_ring/*",
        "advanced_legacy",
        "old polygonal hex-ring notebooks",
        "Publication_Study/outputs/csv/advanced/hexagonal_polygonal_beam_summary.csv",
        "legacy_quarantined",
        "Old polygonal figures predate the focal-plane/propagation-tested split.",
        "diagnostic_legacy",
        source_schema_version=advanced.ADVANCED_BEAM_OUTPUT_SCHEMA_VERSION,
        model_level="diagnostic_only",
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="unknown",
        visualisation_type="legacy_figure",
        recommended_action="Regenerate from canonical advanced CSVs.",
    ),
    _item(
        "Publication_Study/outputs/figures/hex_outline/*",
        "advanced_legacy",
        "old hollow-hex outline notebooks",
        "Publication_Study/outputs/csv/advanced/hexagonal_polygonal_beam_summary.csv",
        "legacy_quarantined",
        "Old hollow-outline figures can imply propagation-stable beams from focal-plane patterns.",
        "diagnostic_legacy",
        source_schema_version=advanced.ADVANCED_BEAM_OUTPUT_SCHEMA_VERSION,
        model_level="diagnostic_only",
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="unknown",
        visualisation_type="legacy_figure",
        recommended_action="Regenerate under Stage 8 propagation/focal-plane labels.",
    ),
    _item(
        "Publication_Study/outputs/csv/stage_f/*",
        "materials_legacy",
        "old Stage F compatibility notebooks",
        "Publication_Study/outputs/csv/materials/material_*.csv",
        "legacy_quarantined",
        "Superseded by canonical materials and capsule CSVs.",
        "diagnostic_legacy",
        source_schema_version=materials.MATERIAL_OUTPUT_SCHEMA_VERSION,
        model_level="material_proxy",
        material_model_status="planning_proxy",
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="not_applicable",
        visualisation_type="legacy_csv",
        recommended_action="Use outputs/csv/materials or outputs/csv/capsule.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
    ),
    _item(
        "Publication_Study/outputs/csv/stage9_capsule/*",
        "capsule_legacy",
        "notebooks/advanced/01_capsule_weld_feature_design.ipynb",
        "Publication_Study/outputs/csv/capsule/*.csv",
        "legacy_quarantined",
        "Old Stage 9 capsule compatibility CSVs are superseded by capsule/*.csv.",
        "diagnostic_legacy",
        source_schema_version=capsule.CAPSULE_OUTPUT_SCHEMA_VERSION,
        model_level="geometry_proxy",
        material_model_status="planning_proxy",
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="not_applicable",
        visualisation_type="legacy_csv",
        recommended_action="Use outputs/csv/capsule/*.csv.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
    ),
    _item(
        "Publication_Study/outputs/csv/stage_h*/*",
        "advanced_legacy",
        "old advanced notebooks",
        "Publication_Study/outputs/csv/advanced/*.csv",
        "legacy_quarantined",
        "Superseded by canonical advanced CSVs.",
        "diagnostic_legacy",
        source_schema_version=advanced.ADVANCED_BEAM_OUTPUT_SCHEMA_VERSION,
        model_level="diagnostic_only",
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="not_applicable",
        visualisation_type="legacy_csv",
        recommended_action="Use outputs/csv/advanced/*.csv.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
    ),
    _item(
        "Publication_Study/outputs/csv/stage10_discrete/*",
        "advanced_legacy",
        "old advanced discrete notebook",
        "Publication_Study/outputs/csv/advanced/discrete_nfold_beam_summary.csv",
        "legacy_quarantined",
        "Superseded by canonical advanced discrete CSVs.",
        "diagnostic_legacy",
        source_schema_version=advanced.ADVANCED_BEAM_OUTPUT_SCHEMA_VERSION,
        model_level="diagnostic_only",
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="not_applicable",
        visualisation_type="legacy_csv",
        recommended_action="Use outputs/csv/advanced/discrete_nfold_*.csv.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
    ),
    _item(
        "Publication_Study/outputs/csv/polygonal_hex_ring/*",
        "advanced_legacy",
        "old polygonal hex-ring notebooks",
        "Publication_Study/outputs/csv/advanced/hexagonal_polygonal_beam_summary.csv",
        "legacy_quarantined",
        "Superseded by canonical advanced hexagonal/polygonal CSVs.",
        "diagnostic_legacy",
        source_schema_version=advanced.ADVANCED_BEAM_OUTPUT_SCHEMA_VERSION,
        model_level="diagnostic_only",
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="not_applicable",
        visualisation_type="legacy_csv",
        recommended_action="Use outputs/csv/advanced/hexagonal_polygonal_*.csv.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
    ),
    _item(
        "Publication_Study/outputs/csv/hex_outline/*",
        "advanced_legacy",
        "old hollow-hex outline notebooks",
        "Publication_Study/outputs/csv/advanced/hexagonal_polygonal_beam_summary.csv",
        "legacy_quarantined",
        "Superseded by canonical advanced hexagonal/polygonal CSVs.",
        "diagnostic_legacy",
        source_schema_version=advanced.ADVANCED_BEAM_OUTPUT_SCHEMA_VERSION,
        model_level="diagnostic_only",
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="not_applicable",
        visualisation_type="legacy_csv",
        recommended_action="Use outputs/csv/advanced/hexagonal_polygonal_*.csv.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
    ),
    _item(
        "Publication_Study/outputs/csv/interface_correction/*",
        "through_sample",
        "legacy interface-correction checkpoints",
        "Publication_Study/outputs/csv/stage_d/*correction*.csv",
        "diagnostic_allowed",
        "Interface-correction checkpoint CSVs are diagnostic and require ideal-correction caveats.",
        "interface_correction",
        source_schema_version=lab_realism.LAB_REALISM_SCHEMA_VERSION,
        model_level="interface_model",
        hardware_status="diagnostic_only",
        visual_quality_status="diagnostic_only",
        pixelation_status="not_applicable",
        visualisation_type="diagnostic_csv",
        recommended_action="Use stage_d correction CSVs for governed exports.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/csv/polarized_train/*",
        "vector_advanced",
        "legacy polarized train checkpoints",
        "Publication_Study/outputs/csv/vector/vector_*.csv",
        "diagnostic_allowed",
        "Polarized-train CSVs are route diagnostics and not current-lab radial/azimuthal proof.",
        "vector_current_lab",
        source_schema_version=vector.VECTOR_OUTPUT_SCHEMA_VERSION,
        model_level="vector_jones",
        hardware_status="diagnostic_only",
        visual_quality_status="diagnostic_only",
        pixelation_status="not_applicable",
        visualisation_type="diagnostic_csv",
        recommended_action="Use canonical vector CSVs for final exports.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/stage7_materials/*",
        "materials_legacy",
        "old Stage 7 materials outputs",
        "Publication_Study/outputs/csv/materials/material_*.csv",
        "legacy_quarantined",
        "Old materials output root is superseded by outputs/csv/materials.",
        "diagnostic_legacy",
        source_schema_version=materials.MATERIAL_OUTPUT_SCHEMA_VERSION,
        model_level="material_proxy",
        material_model_status="planning_proxy",
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="unknown",
        visualisation_type="legacy_output",
        recommended_action="Use outputs/csv/materials canonical tables.",
    ),
    _item(
        "Publication_Study/outputs/stage_g_validation/*",
        "validation_legacy",
        "old Stage G validation outputs",
        "Publication_Study/outputs/csv/publication_study/validation_suite.csv",
        "diagnostic_allowed",
        "Old validation output root is retained for comparison; canonical validation CSVs and figures are allow-listed separately.",
        "validation",
        source_schema_version=tables.SCALAR_OUTPUT_SCHEMA_VERSION,
        model_level="validation",
        visual_quality_status="diagnostic_only",
        pixelation_status="review_at_manuscript_size",
        visualisation_type="validation_diagnostic_output",
        recommended_action="Use current publication_study validation outputs for final exports.",
    ),
    _item(
        "Publication_Study/outputs/csv/quicklook/*",
        "quicklook",
        "notebooks/quicklook/00_quick_beam_to_sample_simulator.ipynb",
        "Publication_Study/outputs/csv/quicklook/quicklook_metric_summary.csv",
        "diagnostic_allowed",
        "Stage 8.7 quick-look metric tables are diagnostic and blocked from final export by default.",
        "quicklook_diagnostic",
        source_schema_version="8.7.0",
        model_level="diagnostic_quicklook",
        hardware_status="row_level",
        material_model_status="planning_proxy",
        propagation_power_label="row_level",
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="quicklook_csv",
        recommended_action="Use for interactive review only; rerun governed stages for final exports.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/json/quicklook/*",
        "quicklook",
        "notebooks/quicklook/00_quick_beam_to_sample_simulator.ipynb",
        "Publication_Study/outputs/csv/quicklook/quicklook_metric_summary.csv",
        "diagnostic_allowed",
        "Stage 8.7 quick-look JSON configs are run metadata, not paper outputs.",
        "quicklook_diagnostic",
        source_schema_version="8.7.0",
        model_level="diagnostic_quicklook",
        hardware_status="row_level",
        material_model_status="planning_proxy",
        propagation_power_label="row_level",
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="quicklook_json",
        recommended_action="Use for traceability and parameter review only.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="yes",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/figures/quicklook/*.png*",
        "quicklook",
        "notebooks/quicklook/00_quick_beam_to_sample_simulator.ipynb",
        "Publication_Study/outputs/csv/quicklook/quicklook_metric_summary.csv",
        "diagnostic_allowed",
        "Stage 8.7 quick-look figures are diagnostic, with visual-only interpolation labelled where used.",
        "quicklook_diagnostic",
        source_schema_version="8.7.0",
        model_level="diagnostic_quicklook",
        hardware_status="row_level",
        material_model_status="planning_proxy",
        propagation_power_label="row_level",
        visual_quality_status="diagnostic_only",
        pixelation_status="acceptable",
        visualisation_type="quicklook_figure",
        recommended_action="Do not export as a final figure; rerun the governed stage at balanced/publication sampling.",
        interpolation_used="yes",
        interpolation_label_present="yes",
        units_present="yes",
        colourbar_label_present="yes",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/manifests/*",
        "manifest",
        "finalize_publication_outputs.py",
        "",
        "diagnostic_allowed",
        "Run manifests are traceability artifacts, not paper figures.",
        "governance_registry",
        source_schema_version=FIGURE_REGISTRY_SCHEMA_VERSION,
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="manifest",
        recommended_action="Use for traceability only.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
    ),
    _item(
        "Publication_Study/outputs/pytest*",
        "runtime",
        "pytest",
        "",
        "rejected",
        "Test/runtime artifacts are never publication outputs.",
        "rejected",
        visual_quality_status="rejected",
        pixelation_status="not_applicable",
        visualisation_type="runtime_artifact",
        recommended_action="Never export.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
    ),
    _item(
        "Publication_Study/outputs/notebook_check/*",
        "runtime",
        "notebook check tooling",
        "",
        "diagnostic_allowed",
        "Notebook execution check artifacts are diagnostics only.",
        "diagnostic_legacy",
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="runtime_diagnostic",
        recommended_action="Do not include in final reports.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
    ),
    _item(
        "Publication_Study/outputs/csv/publication_study/*.png*",
        "rejected_misplaced_artifact",
        "unknown",
        "",
        "rejected",
        "Image or sidecar under csv/publication_study is a misplaced legacy artifact.",
        "rejected",
        visual_quality_status="rejected",
        pixelation_status="unknown",
        visualisation_type="misplaced_artifact",
        recommended_action="Do not export; use figures/publication_study validation figures instead.",
    ),
    _item(
        "Publication_Study/outputs/**/captions_manifest.jsonl",
        "caption_manifest",
        "vbb_style.save_figure/finalize_publication_outputs.py",
        "",
        "diagnostic_allowed",
        "Caption manifests are traceability artifacts, not direct publication figures.",
        "governance_registry",
        source_schema_version=FIGURE_REGISTRY_SCHEMA_VERSION,
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="caption_manifest",
        recommended_action="Use for traceability and caption review only.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
        units_present="not_applicable",
        colourbar_label_present="not_applicable",
        qa_label_visible="yes",
    ),
    _item(
        "Publication_Study/outputs/holograms/stage10_discrete/*",
        "advanced_legacy",
        "old advanced discrete notebook",
        "Publication_Study/outputs/csv/advanced/discrete_nfold_beam_summary.csv",
        "legacy_quarantined",
        "Old discrete CGH outputs predate Stage 8 canonical export labels.",
        "diagnostic_legacy",
        source_schema_version=advanced.ADVANCED_BEAM_OUTPUT_SCHEMA_VERSION,
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="unknown",
        visualisation_type="legacy_hologram",
        recommended_action="Regenerate only through a governed Stage 8 output.",
    ),
    _item(
        "Publication_Study/outputs/holograms/hex_outline/*",
        "advanced_legacy",
        "old hollow-hex outline notebook",
        "Publication_Study/outputs/csv/advanced/hexagonal_polygonal_beam_summary.csv",
        "legacy_quarantined",
        "Old hollow-outline hologram output predate Stage 8 canonical export labels.",
        "diagnostic_legacy",
        source_schema_version=advanced.ADVANCED_BEAM_OUTPUT_SCHEMA_VERSION,
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="unknown",
        visualisation_type="legacy_hologram",
        recommended_action="Regenerate only through a governed Stage 8 output.",
    ),
    _item(
        "Publication_Study/outputs/holograms/*",
        "hologram_diagnostics",
        "various notebooks",
        "",
        "diagnostic_allowed",
        "Hologram/mask outputs are useful for lab review but not paper figures without exact route labels.",
        "diagnostic_legacy",
        visual_quality_status="diagnostic_only",
        pixelation_status="unknown",
        visualisation_type="hologram_or_mask",
        recommended_action="Use as lab artifact only unless separately allow-listed.",
    ),
    _item(
        "Publication_Study/outputs/json/*",
        "metadata_outputs",
        "various notebooks",
        "",
        "diagnostic_allowed",
        "JSON metadata and diagnostics are not direct publication figures.",
        "diagnostic_legacy",
        visual_quality_status="table_or_metadata",
        pixelation_status="not_applicable",
        visualisation_type="metadata_json",
        recommended_action="Use for traceability, not final figure export.",
        interpolation_used="not_applicable",
        interpolation_label_present="not_applicable",
    ),
    _item(
        "Publication_Study/archive/old_outputs/*",
        "archive",
        "archive",
        "",
        "legacy_quarantined",
        "Archived old outputs are retained for traceability only.",
        "diagnostic_legacy",
        visual_quality_status="legacy_not_reviewed",
        pixelation_status="unknown",
        visualisation_type="archive_artifact",
        recommended_action="Never use silently in final publication exports.",
    ),
)


_UNKNOWN_ITEM = _item(
    "<unknown>",
    "unknown",
    "unknown",
    "",
    "rejected",
    "No registry entry matched this output path.",
    "rejected",
    caveat_required=True,
    visual_quality_status="rejected",
    pixelation_status="unknown",
    visualisation_type="unknown_artifact",
    recommended_action="Add a registry entry before export.",
)


def _normalise_path(path: str | Path) -> str:
    text = str(path).replace("\\", "/").strip()
    while text.startswith("./"):
        text = text[2:]
    if text.startswith("outputs/"):
        text = f"Publication_Study/{text}"
    if text.startswith("figures/") or text.startswith("csv/") or text.startswith("holograms/") or text.startswith("json/"):
        text = f"Publication_Study/outputs/{text}"
    return text


def registry_items() -> tuple[FigureRegistryItem, ...]:
    """Return the immutable Stage 8.6 registry entries."""

    return _REGISTRY_ITEMS


def _match_score(pattern: str, path: str) -> int:
    if fnmatch.fnmatchcase(path.lower(), pattern.lower()):
        return len(pattern.replace("*", ""))
    return -1


def classify_path(path: str | Path) -> FigureRegistryItem:
    """Return the best registry item for a concrete path or path pattern."""

    normalised = _normalise_path(path)
    best: tuple[int, FigureRegistryItem] | None = None
    for item in registry_items():
        score = _match_score(_normalise_path(item.output_path), normalised)
        if score < 0:
            continue
        if best is None or score > best[0]:
            best = (score, item)
    if best is None:
        return _UNKNOWN_ITEM
    return best[1]


def assert_export_allowed(path: str | Path) -> FigureRegistryItem:
    """Return the registry item if ``path`` is final-export allowed.

    Raises
    ------
    PublicationExportGateError
        If the path is diagnostic, exploratory, legacy, rejected, or unknown.
    """

    item = classify_path(path)
    if not item.final_export_allowed:
        raise PublicationExportGateError(
            f"{path!s} is not final-export allowed: status={item.status}; reason={item.reason}"
        )
    return item


def registry_rows() -> list[dict[str, object]]:
    """Return registry rows with caption-gate caveats attached."""

    rows: list[dict[str, object]] = []
    for item in registry_items():
        gate = caption_gate(item.caption_gate_key)
        row = asdict(item)
        row["registry_schema_version"] = FIGURE_REGISTRY_SCHEMA_VERSION
        row["caption_text"] = gate.caption_text
        row["caveat_text"] = gate.caveat_text
        row["caption_gate_export_allowed"] = gate.export_allowed
        row["warning_level"] = gate.warning_level
        rows.append(row)
    return rows


def registry_frame() -> pd.DataFrame:
    """Return the registry as a DataFrame."""

    return pd.DataFrame(registry_rows())


def visual_quality_rows() -> list[dict[str, object]]:
    """Return the Stage 8.6 visual QA table rows."""

    rows: list[dict[str, object]] = []
    for item in registry_items():
        gate = caption_gate(item.caption_gate_key)
        rows.append(
            {
                "stage": item.stage,
                "notebook": item.notebook_source,
                "figure_or_output": item.output_path,
                "visualisation_type": item.visualisation_type,
                "final_export_allowed": bool(item.final_export_allowed),
                "diagnostic_allowed": item.status == "diagnostic_allowed",
                "legacy_quarantined": item.status == "legacy_quarantined",
                "pixelation_status": item.pixelation_status,
                "interpolation_used": item.interpolation_used,
                "interpolation_label_present": item.interpolation_label_present,
                "units_present": item.units_present,
                "colourbar_label_present": item.colourbar_label_present,
                "qa_label_visible": item.qa_label_visible,
                "caveat_present": bool(gate.caveat_text),
                "source_run_id": item.source_run_id,
                "source_schema_version": item.source_schema_version,
                "recommended_action": item.recommended_action,
            }
        )
    return rows


def visual_quality_frame() -> pd.DataFrame:
    """Return the Stage 8.6 visual QA table as a DataFrame."""

    columns = [
        "stage",
        "notebook",
        "figure_or_output",
        "visualisation_type",
        "final_export_allowed",
        "diagnostic_allowed",
        "legacy_quarantined",
        "pixelation_status",
        "interpolation_used",
        "interpolation_label_present",
        "units_present",
        "colourbar_label_present",
        "qa_label_visible",
        "caveat_present",
        "source_run_id",
        "source_schema_version",
        "recommended_action",
    ]
    return pd.DataFrame(visual_quality_rows(), columns=columns)


def write_registry_outputs(output_dir: str | Path) -> dict[str, Path]:
    """Write the registry and visual QA CSVs to ``output_dir``."""

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    registry_path = out / "figure_output_registry.csv"
    visual_path = out / "figure_visual_quality_audit.csv"
    registry_frame().to_csv(registry_path, index=False)
    visual_quality_frame().to_csv(visual_path, index=False)
    return {"registry": registry_path, "visual_quality": visual_path}


def validate_registry(items: Iterable[FigureRegistryItem] | None = None) -> list[str]:
    """Return human-readable validation errors for registry consistency."""

    errors: list[str] = []
    selected = tuple(registry_items() if items is None else items)
    for item in selected:
        if item.status not in STATUS_VALUES:
            errors.append(f"{item.output_path}: invalid status {item.status!r}")
        if item.status == "legacy_quarantined" and item.final_export_allowed:
            errors.append(f"{item.output_path}: legacy item cannot be final_export_allowed")
        if item.final_export_allowed:
            if not item.stage or item.stage == "unknown":
                errors.append(f"{item.output_path}: final-export item missing stage")
            if not item.caption_gate_key:
                errors.append(f"{item.output_path}: final-export item missing caption gate")
            if item.visual_quality_status in {"legacy_not_reviewed", "rejected"}:
                errors.append(f"{item.output_path}: final-export item has unsafe visual quality status")
            gate = caption_gate(item.caption_gate_key)
            if item.caveat_required and not gate.caveat_text:
                errors.append(f"{item.output_path}: required caveat is empty")
    return errors


__all__ = [
    "FIGURE_REGISTRY_SCHEMA_VERSION",
    "PIXELATION_STATUS",
    "STATUS_VALUES",
    "VISUAL_QUALITY_STATUS",
    "FigureRegistryItem",
    "PublicationExportGateError",
    "assert_export_allowed",
    "classify_path",
    "registry_frame",
    "registry_items",
    "registry_rows",
    "validate_registry",
    "visual_quality_frame",
    "visual_quality_rows",
    "write_registry_outputs",
]
