"""Corrected orchestrator for the extended Phase 2I presentation evidence.

The first inverse proof-of-principle deliberately hit the repository guard that
fixed-plane diagnostics require at least sixteen z planes.  This orchestrator
keeps that guard and uses seventeen planes rather than weakening the contract.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

import build_presentation_extended_evidence as ext
from vbb_study.digital_twin.vortex_system_route import AxiconError, SystemErrorConfig, build_system_route


def build_synthetic_inverse_recovery(out: Path, grid_n: int) -> tuple[Path, dict]:
    z = np.linspace(20e-3, 100e-3, 17)
    coord = np.linspace(-0.75e-3, 0.75e-3, 241)
    truth = 300e-6
    candidates = np.arange(-500e-6, 500.1e-6, 100e-6)

    target_route = build_system_route(
        "V1",
        grid_n=int(grid_n),
        config=SystemErrorConfig(axicon=AxiconError(decentre_m=(truth, 0.0))),
    )
    target, retained_truth = ext._xz(
        target_route,
        coord,
        z_values_m=z,
        label="synthetic-inverse-truth-17-plane",
    )

    costs: list[float] = []
    maps: list[np.ndarray] = []
    retained: list[float] = []
    for value in candidates:
        route = build_system_route(
            "V1",
            grid_n=int(grid_n),
            config=SystemErrorConfig(axicon=AxiconError(decentre_m=(float(value), 0.0))),
        )
        xz, ret = ext._xz(
            route,
            coord,
            z_values_m=z,
            label=f"synthetic-inverse-17-plane-{value:g}",
        )
        maps.append(xz)
        retained.append(ret)
        costs.append(ext._stack_cost(xz, target))

    best = int(np.argmin(costs))
    recovered = float(candidates[best])
    nominal_idx = int(np.argmin(np.abs(candidates)))

    fig = plt.figure(figsize=(12.6, 6.3), constrained_layout=True)
    ext._style_fig(fig)
    gs = fig.add_gridspec(2, 3, width_ratios=[1.0, 1.0, 1.15])

    ax0 = fig.add_subplot(gs[0, 0])
    ext._draw_xz(ax0, target, coord, z, ylabel=True)
    ax0.set_title("synthetic target\nunknown to inverse", color=ext.TEXT, fontsize=11)

    ax1 = fig.add_subplot(gs[0, 1])
    ext._draw_xz(ax1, maps[nominal_idx], coord, z, ylabel=False)
    ax1.set_title("nominal model\n0 µm", color=ext.TEXT, fontsize=11)

    ax2 = fig.add_subplot(gs[0, 2])
    ext._style_ax(ax2)
    ax2.plot(candidates * 1e6, costs, marker="o", lw=1.4)
    ax2.axvline(truth * 1e6, color=ext.GREEN, ls="--", lw=1.2, label="truth")
    ax2.axvline(recovered * 1e6, color=ext.RED, ls=":", lw=1.5, label="recovered")
    ax2.set_xlabel("candidate axicon decentre (µm)", fontsize=9)
    ax2.set_ylabel("multi-plane normalized L2", fontsize=9)
    ax2.set_title("inverse cost over 17 z planes", fontsize=11)
    ax2.legend(frameon=False, labelcolor=ext.TEXT, fontsize=8)

    ax3 = fig.add_subplot(gs[1, 0])
    ext._style_ax(ax3)
    residual_nom = ext._norm(maps[nominal_idx]) - ext._norm(target)
    vmax = max(float(np.max(np.abs(residual_nom))), ext.EPS)
    ax3.imshow(
        residual_nom.T,
        origin="lower",
        extent=[z[0] * 1e3, z[-1] * 1e3, coord[0] * 1e3, coord[-1] * 1e3],
        cmap="coolwarm",
        vmin=-vmax,
        vmax=vmax,
        aspect="auto",
    )
    ax3.set_title("nominal − target residual", fontsize=11)
    ax3.set_xlabel("z (mm)", fontsize=8)
    ax3.set_ylabel("x (mm)", fontsize=8)

    ax4 = fig.add_subplot(gs[1, 1])
    ext._draw_xz(ax4, maps[best], coord, z, ylabel=False)
    ax4.set_title(f"best fit\n{recovered * 1e6:+.0f} µm", color=ext.TEXT, fontsize=11)

    ax5 = fig.add_subplot(gs[1, 2])
    ax5.set_facecolor(ext.FIG_BG)
    ax5.axis("off")
    ax5.text(0.02, 0.82, "proof of principle", color=ext.RED, fontsize=11, weight="bold")
    ax5.text(0.02, 0.67, f"hidden decentre: {truth * 1e6:+.0f} µm", color=ext.TEXT, fontsize=13)
    ax5.text(0.02, 0.54, f"recovered: {recovered * 1e6:+.0f} µm", color=ext.GREEN, fontsize=13, weight="bold")
    ax5.text(
        0.02,
        0.36,
        "many z planes constrain one\nphysical bench parameter better\nthan one camera plane alone.",
        color=ext.MUTED,
        fontsize=11,
        linespacing=1.5,
    )
    ax5.text(
        0.02,
        0.10,
        "Next layer: fit a vector of beam / SLM / 4F /\nlow-order wavefront parameters, then compute\nan additive correction map.",
        color=ext.TEXT,
        fontsize=9,
        linespacing=1.4,
    )

    fig.suptitle(
        "Synthetic z-stack inverse recovery — model-to-model validation",
        color=ext.TEXT,
        fontsize=16,
        y=1.03,
    )
    fig.text(
        0.5,
        -0.015,
        "This is not an experimental reconstruction: the target stack is generated by the same forward-model family with a hidden physical parameter.",
        color="#f2c14e",
        ha="center",
        fontsize=9,
    )

    path = ext._save(fig, out / "10_synthetic_zstack_inverse_recovery.png")
    meta = {
        "truth_axicon_decentre_m": truth,
        "candidate_axicon_decentre_m": candidates.tolist(),
        "costs": costs,
        "recovered_axicon_decentre_m": recovered,
        "z_planes_m": z.tolist(),
        "grid_n": int(grid_n),
        "fixed_support_retained_power_fraction_truth": retained_truth,
        "fixed_support_retained_power_fraction_candidates": retained,
        "claim_boundary": "synthetic model-to-model inverse proof-of-principle; not experimental aberration recovery",
    }
    return path, meta


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--grid-n", type=int, default=1024)
    parser.add_argument("--inverse-grid-n", type=int, default=512)
    parser.add_argument("--output-dir", type=Path, default=Path("outputs/figures/presentation_phase2i"))
    args = parser.parse_args()
    if args.grid_n < 1024:
        raise ValueError("main extended presentation figures require grid_n >= 1024")
    if args.inverse_grid_n < 384:
        raise ValueError("inverse screening grid must be >= 384")

    out = args.output_dir
    out.mkdir(parents=True, exist_ok=True)
    p7, m7 = ext.build_beam_profile_hero(out, args.grid_n)
    p8, m8 = ext.build_real_error_fingerprints(out, args.grid_n)
    p9, m9 = ext.build_tip_avoidance_proxy(out, args.grid_n)
    p10, m10 = build_synthetic_inverse_recovery(out, args.inverse_grid_n)

    manifest = {
        "outcome": "PRESENTATION-EXTENDED-EVIDENCE-V2",
        "source_branch_contract": "phase2i-experimental-bench-closure",
        "figures": [str(p) for p in (p7, p8, p9, p10)],
        "beam_profile_hero": m7,
        "real_error_fingerprints": m8,
        "tip_avoidance_planning_proxy": m9,
        "synthetic_inverse_recovery": m10,
        "fixed_plane_contract": "17 z planes used for inverse proof; repository minimum is 16",
    }
    (out / "presentation_extended_manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
